### ISSUE TITLE
Break source files into two

### ISSUE THREAD

**Issue by neauoire** [tbsp/varaboy#2]
Do you think you could break the source down into two files, where one is the main part of the code, and the second the `SM83 Instruction Jump Table` portion with all the opcodes?

The main reason is that it's too large to be opened all at once in Left XD

**Comment by tbsp** [comment]
I've broken it up a bit more than that, as the MBC code seems worth keeping separate as well, and the memory map likely won't ever change. The opcodes.tal file seems viewable all the way to the end in Left now.

I just realized both opcodes.tal and varaboy.tal are currently 875 lines. Neat.
